{ pkgs, lib, customPkgs, ... }:

{
  home.packages = with pkgs; [
    chafa
    bat
    eza
    fd
    fzf
    jq
    d2
    ripgrep
    yazi
    home-manager
    superfile
    grim
    slurp
    wev
    wf-recorder
    sway-contrib.grimshot
    libnotify
    dockfmt
    nixfmt
    shellcheck
    shfmt
    obs-studio
    zed-editor
    neovim
    git
    gh
    lua
    lua-language-server
    luaPackages.lgi
    lazygit
    aider-chat
    desktop-file-utils
    cargo
    openssl
    pkg-config
    rust-analyzer
    rustc
    rustfmt
    black
    isort
    nmap
    pulseview
    (python3.withPackages (
      ps: with ps; [
        pip
        pyglet
        pdfplumber
      ]
    ))
    terraform
    kubeconform
    minikube
    (lib.hiPrio kubectl)
    (lib.lowPrio k3s)
    typescript-language-server
    vscode-langservers-extracted
    tailwindcss-language-server
    nodejs_22
    pnpm
    yarn
    aspell
    aspellDicts.en
    aspellDicts.en-computers
    aspellDicts.fr
    papirus-icon-theme
    swaynotificationcenter
    cava
    cool-retro-term
    nerd-fonts.symbols-only
    hyprcursor
    rose-pine-hyprcursor
    nerd-fonts.jetbrains-mono
    bibata-cursors
    conky
    adw-gtk3
    gnome-themes-extra
    pywal
    wpgtk
    qt6Packages.qtbase
    qt6Packages.qt6ct
    qt6Packages.qttools
    kdePackages.qtstyleplugin-kvantum
    libsForQt5.qtstyleplugin-kvantum
    socat
    atop
    bottom
    btop
    glances
    htop
    nvitop
    nvtopPackages.full
    hyprlock
    hypridle
    brightnessctl
    playerctl
    appimage-run
    discord
    spotify
    cbonsai
    cmatrix
    hollywood
    pipes
    sl
    customPkgs.terminal-rain-lightning
    dart-sass
  ];
}
