plugin:darkwindow:tint_r        = 0.20
plugin:darkwindow:tint_g        = 0.70
plugin:darkwindow:tint_b        = 1.00
plugin:darkwindow:tint_strength = 0.058

plugin:darkwindow:protect_brights      = 1.00
plugin:darkwindow:bright_threshold     = 0.55
plugin:darkwindow:bright_knee          = 0.35
plugin:darkwindow:protect_saturated    = 1.00
plugin:darkwindow:saturation_threshold = 0.05
plugin:darkwindow:saturation_knee      = 0.25

plugin:darkwindow:enable_on_fullscreen = 0
plugin:darkwindow:tint_all_surfaces    = 1
plugin:darkwindow:suspend_on_workspace_switch_ms = 150

# Toggle global
bind = SUPER, P, exec, hyprctl dispatch togglechromakey
