general {
  col.active_border = rgba(94e2d5ff)
  col.inactive_border = rgba(ffffff14)
  border_size = 2
  gaps_in = 8
  gaps_out = 16
}

decoration {
  rounding = 12

  active_opacity = 0.57
  inactive_opacity = 0.57

  blur {
    enabled = true

    size = 5
    passes = 5

    ignore_opacity = true
    noise = 0.01
    contrast = 1
    brightness = 1.2
    xray = true
    vibrancy = 0.10
  }

  shadow {
    enabled = true
    range = 30
    render_power = 3
    color = rgba(00000022)
  }
}
