# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # --- Kernel Modules ---
  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # --- Filesystems ---
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/81622f02-7f85-42d9-ba8f-e29216a6f869";
    fsType = "ext4";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/32bf39cf-49e9-42b4-b0f3-6decc3abdc1d";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/C2D7-25B7";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  # --- Swap ---
  swapDevices = [
    { device = "/dev/disk/by-uuid/a4fa3a47-8ff2-4551-ae26-4414891817cd"; }
  ];

  # --- Networking & CPU ---
  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
