# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # --- Kernel Modules ---
  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # --- Filesystems ---
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/80f8e314-a63c-4f85-88fb-2cb6a3f33430";
    fsType = "ext4";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/31967aa1-d0f2-4ff6-ad9b-aa6a4000edb7";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/C2D7-25B7";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  # --- Swap ---
  swapDevices = [
    { device = "/dev/disk/by-uuid/990989c3-b2b4-410c-87a2-239ad865c3a3"; }
  ];

  # --- Networking & CPU ---
  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
